Add update notification opt out policy
microsoft/Visual-Studio-Administrative-Templates pull request #118
Opened 2024-08-21 17:59 UTC by jlee671

Add update notification in VS opt out policy to ADMX and update other aka.ms link to https

![image](https://github.com/user-attachments/assets/73c1531a-a419-481d-8bdc-f321daec0204)

2024-08-21 22:28 UTC, tydunkel requested changes

2024-08-21 22:28 UTC, tydunkel commented on settingFiles/admx/en-US/VisualStudio.adml
> +If set to a 1, then the update notification in the Visual Studio IDE will be suppressed for the Enterprise and Professional editions on release or ltsc channel, only if they are either receiving upda
I think Release and LTS should be capitalized.

```
If set to 1, the update notification in the Visual Studio IDE will be suppressed for the Enterprise and Professional editions on the Release or LTS channels, only if they are either receiving updates from a layout or if they are enrolled to receive Visual Studio Administrator Updates.
```

Not sure how I feel about the mentioning about use cases. I don't think our documentation here should call out why someone would want to use it, they can choose when they want

2024-08-22 17:12 UTC, jlee671 commented on settingFiles/admx/en-US/VisualStudio.adml
> +If set to a 1, then the update notification in the Visual Studio IDE will be suppressed for the Enterprise and Professional editions on release or ltsc channel, only if they are either receiving upda
Hmm yea, I think it should be more of instructions than explaining use case.

2024-08-22 17:46 UTC, christineruana commented on settingFiles/admx/en-US/VisualStudio.adml
> +If set to a 1, then the update notification in the Visual Studio IDE will be suppressed for the Enterprise and Professional editions on release or ltsc channel, only if they are either receiving upda
I'll add these scenarios to the online docs instead of the admx content then.  People have explicitly asked me for this type of best practice & guidance (i.e. what do I use when).

2024-08-22 17:47 UTC, christineruana commented on settingFiles/admx/en-US/VisualStudio.adml
> +If set to a 1, the update notification in the Visual Studio IDE will be suppressed for the Enterprise and Professional editions on the Release or LTS channels, only if they are either receiving updat
```suggestion
If set to a 1, the update notification in the Visual Studio IDE will be suppressed for the Enterprise and Professional editions on the Release or LTSC channels, only if they are either receiving updates from a layout or if they are enrolled to receive Visual Studio Administrator Updates.
```

2024-08-22 17:48 UTC, christineruana commented
Also, thank you for fixing all the https: issues.

2024-08-22 18:17 UTC, jlee671 commented on settingFiles/admx/en-US/VisualStudio.adml
> +If set to a 1, the update notification in the Visual Studio IDE will be suppressed for the Enterprise and Professional editions on the Release or LTS channels, only if they are either receiving updat
@christineruana The "C" in "LTSC" already stands for "channel". Do we want to say "the Release channel or LTSC" then?

2024-08-22 18:18 UTC, skylarnam requested changes

2024-08-22 18:18 UTC, skylarnam commented on settingFiles/admx/VisualStudio.admx
> +			<definition name="VisualStudio2022_12AndHigher" displayName="$(string.VisualStudio2022_12)">
nit: whitespace?

2024-08-22 18:18 UTC, skylarnam commented on settingFiles/admx/VisualStudio.admx
> +		<policy
nit: whitespace?

2024-08-22 18:18 UTC, skylarnam commented on settingFiles/admx/en-US/VisualStudio.adml
> +	  <string id="UpdateNotificationsOptOut_DisplayName">Disable update notifications in Visual Studio</string>
nit: whitespace

2024-08-22 18:30 UTC, jlee671 commented on settingFiles/admx/en-US/VisualStudio.adml
> +If set to a 1, the update notification in the Visual Studio IDE will be suppressed for the Enterprise and Professional editions on the Release or LTS channels, only if they are either receiving updat
Chatted offline, going with her original suggestion

2024-08-22 20:23 UTC, tydunkel approved these changes

2024-08-22 20:35 UTC, skylarnam commented on settingFiles/admx/VisualStudio.admx
> +			<parentCategory ref="InstallandUpdateSettings" />
nit: whitespace

2024-08-22 20:36 UTC, skylarnam approved these changes

2024-08-23 19:56 UTC, skylarnam approved these changes

2024-08-23 19:58 UTC, merged